---
title: "Gov 50 Final Project"
author: "Atticus Lee"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to universal basic income. I would like to explore how a UBI or stimulus check affects economic trends, crime rates, education, and ideology.

## Milestone 2

What effect does unemployment insurance have on life expectancy? In this study, I plan to examine how changes in unemployment insurance replacement rates and total coverage impacts life expectancy at age 65. I hypothesize that higher replacement rates and coverage increases average life expectancy. I also expect that lower replacement rates and coverage will decrease average life expectancy. I expect these to occur because more money given to more people would increase standard of living and possibly lifespan. My sample is comprised of different
institutional features of national social insurance programs in 27 OECD and 6 non‐OECD countries from the years 1970 to 2011. My explanatory variables of interest are replacement rates and total coverage. Replacement rates are coded on a scale from 0 to 1, representing the percentage of a wage that becomes the benefit. Total coverage is also coded on a scale from 0 to 1, representing the percentage of the labor force insured for unemployment risk. My outcome variable is national life expectancy at age 65, which is coded as the number of years expected to live after the age of 65. For example if the variable = 10, it means life expectancy is 65 + 10 = 75. These variables are measured from the Comparative Welfare Entitlements Dataset, a comprehensive welfare dataset run by Professor Lyle Scruggs and funded by the National Science Foundation and German Research Foundation. If I observe higher life expectancy on average for countries with higher replacement rates and coverage than those with lower replacement rates and coverage, this would provide support to my hypothesis. If I observe lower or similar life expectancy on average for countries with higher replacement rates and coverage than those with lower replacement rates and coverage, this would provide evidence against my hypothesis. When I run my regression of the life expectancy on the replacement rate and coverage indicator variables, a positive, significant coefficient would indicate support for my hypothesis.

